MAX_UNAME_CHARS = 32
MAX_PWD_CHARS = MAX_UNAME_CHARS
MIN_PWD_CHARS = 8

MAX_TAGS_CHARS = 50
MAX_TAGS_N_PER_PROD = 100

MAX_PROD_NOME_CHARS = 100
MAX_PROD_DESC_BR_CHARS = 255
MAX_PROD_DESC_CHARS = 3000
MIN_PROD_PREZZO_VALUE = 1.00
MAX_PROD_PREZZO_DIGITS_DECIMAL = (8,2)
MAX_PROD_PREZZO_VALUE = float('9' * (MAX_PROD_PREZZO_DIGITS_DECIMAL[0] - MAX_PROD_PREZZO_DIGITS_DECIMAL[1]) + '.' + '9' * MAX_PROD_PREZZO_DIGITS_DECIMAL[1])
PROD_CONDIZIONE_CHOICES = [
    ('nuovo', 'Nuovo'),
    ('usato', 'Usato')
]

MIN_ANNU_QTA_MAGAZZINO_VALUE = 0
MAX_ANNU_QTA_MAGAZZINO_VALUE = 2000000

MAX_COMMNT_TESTO_CHARS = 1000
MIN_COMMNT_RATING_VALUE = 0
MAX_COMMNT_RATING_VALUE = 5
INVALID_COMMNT_RATING_VALUE = -1
RANGE_COMMNT_RATING_STRING = "".join(str(i) for i in range(1, MAX_COMMNT_RATING_VALUE + 1))

MAX_ORDN_INVOICE_CHARS = 255
MIN_ORDN_QUANTITA_VALUE = 1
ORDN_STATO_CONSEGNA_CHOICES = [
    ('da spedire', 'Da spedire'),
    ('spedito', 'Spedito'),
    ('consegnato', 'Consegnato'),
    ('annullato', 'Annullato')
]

MAX_PAGINATOR_HOME_VALUE = 21
MAX_PAGINATOR_ORDINI_VALUE = 20
MAX_PAGINATOR_ANNUNCI_VALUE = MAX_PAGINATOR_ORDINI_VALUE
MAX_PAGINATOR_RICERCA_VALUE = 50

MIN_CREA_ANNUNCIO_QTA_VALUE = 1

MAX_WS_QUERIES = 10

ALIQUOTA_IVA_ORD = 22
ALIQUOTA_IVA_RID = 10
ALIQUOTA_IVA_URID = 4
ALIQUOTA_IVA_ESE = 0

SYLVELIUS_FEES = 0.02 # 2%

MAX_TRUNCATED_PROFILO_CHARS = 50
MAX_TRUNCATED_CARDS_CHARS = 15

MAX_SLICE_PROFILO_VALUE = 5
MAX_LIST_CLIENTI_VALUE = 3
MAX_SLICE_TAGS_PER_CARD = 3