# Generated by Django 5.2.1 on 2025-06-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=255, unique=True)),
                ('user_id', models.PositiveIntegerField()),
                ('quantita', models.PositiveIntegerField()),
                ('prodotto_id', models.PositiveIntegerField()),
            ],
        ),
    ]
