# Generated by Django 5.2.1 on 2025-06-12 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Iban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iban', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
