# Generated by Django 5.2.1 on 2025-06-20 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_cart_invoice_cart'),
        ('sylvelius', '0029_alter_annuncio_options_alter_prodotto_iva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='prodotto_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='prodotto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='sylvelius.prodotto'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
    ]
