# Generated by Django 5.2.1 on 2025-06-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_remove_invoice_prodotto_id_remove_invoice_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='invoice',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
