# Generated by Django 5.2.1 on 2025-06-20 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_cart_invoice'),
        ('sylvelius', '0029_alter_annuncio_options_alter_prodotto_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='prodotto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoices', to='sylvelius.prodotto'),
        ),
    ]
