# Generated by Django 5.2.1 on 2025-06-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_rename_invoice_cart_uuid_rename_user_invoice_utente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_id',
            new_name='uuid',
        ),
    ]
