# Generated by Django 5.2.1 on 2025-06-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_rename_invoice_id_invoice_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
