# Generated by Django 5.2.1 on 2025-06-30 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_invoice_is_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='is_locked',
        ),
    ]
