# Generated by Django 5.2.1 on 2025-05-23 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pubblicazione', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Creazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('annuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creazioni', to='sylvelius.annuncio')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creazioni', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField()),
                ('stato', models.CharField(choices=[('in attesa', 'In attesa'), ('completato', 'Completato')], default='in attesa', max_length=20)),
                ('data_ordine', models.DateTimeField(auto_now_add=True)),
                ('annuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordini', to='sylvelius.annuncio')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordini', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
