# Generated by Django 5.2.1 on 2025-05-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylvelius', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='annuncio',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='annunci', to='sylvelius.tag'),
        ),
    ]
