# Generated by Django 5.2.1 on 2025-05-24 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylvelius', '0003_annuncio_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annuncio',
            name='immagine',
        ),
        migrations.CreateModel(
            name='ImmagineAnnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='annunci/immagini/')),
                ('annuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immagini', to='sylvelius.annuncio')),
            ],
        ),
    ]
