# Generated by Django 5.2.1 on 2025-05-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylvelius', '0006_alter_ordine_annuncio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='luogo_consegna',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
