# Generated by Django 5.2.1 on 2025-05-27 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylvelius', '0007_ordine_luogo_consegna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annuncio',
            name='descrizione',
        ),
        migrations.RemoveField(
            model_name='annuncio',
            name='prezzo',
        ),
        migrations.RemoveField(
            model_name='annuncio',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='annuncio',
            name='titolo',
        ),
        migrations.RemoveField(
            model_name='ordine',
            name='annuncio',
        ),
        migrations.AddField(
            model_name='annuncio',
            name='qta_magazzino',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descrizione_breve', models.CharField(blank=True, max_length=255, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tags', models.ManyToManyField(blank=True, related_name='prodotti', to='sylvelius.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ImmagineProdotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='prodotti/immagini/')),
                ('prodotto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='immagini', to='sylvelius.prodotto')),
            ],
        ),
        migrations.AddField(
            model_name='annuncio',
            name='prodotto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annunci', to='sylvelius.prodotto'),
        ),
        migrations.AddField(
            model_name='ordine',
            name='prodotto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordini', to='sylvelius.prodotto'),
        ),
        migrations.DeleteModel(
            name='ImmagineAnnuncio',
        ),
    ]
