# Generated by Django 5.2.1 on 2025-05-27 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylvelius', '0008_remove_annuncio_descrizione_remove_annuncio_prezzo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annuncio',
            name='prodotto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annunci', to='sylvelius.prodotto'),
        ),
    ]
