# Generated by Django 5.2.1 on 2025-05-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylvelius', '0010_commentoannuncio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
