# Generated by Django 5.2.1 on 2025-05-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylvelius', '0011_ordine_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='luogo_consegna',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
