# Generated by Django 5.2.1 on 2025-05-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylvelius', '0012_alter_ordine_luogo_consegna'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='stato_consegna',
            field=models.CharField(choices=[('da_spedire', 'Da spedire'), ('spedito', 'Spedito')], default='da_spedire', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordine',
            name='luogo_consegna',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
