# Generated by Django 5.2.1 on 2025-05-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylvelius', '0013_ordine_stato_consegna_alter_ordine_luogo_consegna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=255, unique=True)),
                ('user_id', models.IntegerField()),
                ('quantita', models.PositiveIntegerField()),
                ('prodotto_id', models.IntegerField()),
            ],
        ),
    ]
