# Generated by Django 5.2.1 on 2025-05-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylvelius', '0014_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='descrizione',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='descrizione_breve',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
