# Generated by Django 5.2.1 on 2025-05-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylvelius', '0016_remove_ordine_stato_prodotto_condizione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentoannuncio',
            name='testo',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ordine',
            name='stato_consegna',
            field=models.CharField(choices=[('da spedire', 'Da spedire'), ('spedito', 'Spedito'), ('in transito', 'In transito'), ('consegnato', 'Consegnato'), ('annullato', 'Annullato')], default='da spedire', max_length=20),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='descrizione_breve',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
