# Generated by Django 5.2.1 on 2025-06-01 09:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylvelius', '0017_alter_commentoannuncio_testo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annuncio',
            name='prodotto',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='annunci', to='sylvelius.prodotto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentoannuncio',
            name='testo',
            field=models.TextField(default='commento', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='immagineprodotto',
            name='prodotto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='immagini', to='sylvelius.prodotto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='prodotto_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ordine',
            name='luogo_consegna',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='ordine',
            name='prodotto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordini', to='sylvelius.prodotto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordine',
            name='quantita',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='descrizione_breve',
            field=models.CharField(default='descrizione breve', max_length=255),
            preserve_default=False,
        ),
    ]
