# Generated by Django 5.2.1 on 2025-06-02 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sylvelius', '0018_alter_annuncio_prodotto_alter_commentoannuncio_testo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
