# Generated by Django 5.2.1 on 2025-06-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylvelius', '0019_delete_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='stato_consegna',
            field=models.CharField(choices=[('da spedire', 'Da spedire'), ('spedito', 'Spedito'), ('consegnato', 'Consegnato'), ('annullato', 'Annullato')], default='da spedire', max_length=20),
        ),
    ]
