# Generated by Django 5.2.1 on 2025-06-02 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylvelius', '0020_alter_ordine_stato_consegna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creazione',
            name='annuncio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creazioni', to='sylvelius.annuncio'),
        ),
    ]
