# Generated by Django 5.2.1 on 2025-06-02 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylvelius', '0021_alter_creazione_annuncio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='annuncio',
            name='inserzionista',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='annunci', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Creazione',
        ),
    ]
