# Generated by Django 5.2.1 on 2025-06-03 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylvelius', '0022_annuncio_inserzionista_delete_creazione'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordine',
            old_name='invoice_id',
            new_name='invoice',
        ),
        migrations.AlterField(
            model_name='annuncio',
            name='qta_magazzino',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000000)]),
        ),
        migrations.AlterField(
            model_name='commentoannuncio',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
