# Generated by Django 5.2.1 on 2025-06-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylvelius', '0023_rename_invoice_id_ordine_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annuncio',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
