# Generated by Django 5.2.1 on 2025-06-12 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sylvelius', '0025_alter_tag_nome_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['created_at']},
        ),
    ]
