# Generated by Django 5.2.1 on 2025-06-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylvelius', '0026_alter_notification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='iva',
            field=models.PositiveIntegerField(choices=[(22, '22%'), (10, '10%'), (4, '4%'), (0, '0%')], default=22),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='condizione',
            field=models.CharField(choices=[('nuovo', 'Nuovo'), ('usato', 'Usato')], default='nuovo'),
        ),
    ]
