# Generated by Django 5.2.1 on 2025-06-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylvelius', '0028_alter_ordine_stato_consegna'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annuncio',
            options={'ordering': ['-data_pubblicazione']},
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='iva',
            field=models.PositiveIntegerField(choices=[(22, '22% - Aliquota ordinaria'), (10, '10% - Prodotti alimentari / farmaceutici'), (4, '4% - Dispositivi medici / prima necessità'), (0, '0% - Operazioni esenti')], default=22),
        ),
    ]
