# Generated by Django 5.2.1 on 2025-06-30 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylvelius', '0029_alter_annuncio_options_alter_prodotto_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annuncio',
            name='prodotto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annuncio', to='sylvelius.prodotto'),
        ),
    ]
