# Generated by Django 5.2.1 on 2025-06-30 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sylvelius', '0030_alter_annuncio_prodotto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annuncio',
            options={'ordering': ['-data_pubblicazione'], 'verbose_name_plural': 'Annunci'},
        ),
        migrations.AlterModelOptions(
            name='commentoannuncio',
            options={'verbose_name_plural': 'Commenti Annunci'},
        ),
        migrations.AlterModelOptions(
            name='immagineprodotto',
            options={'verbose_name_plural': 'Immagini Prodotti'},
        ),
        migrations.AlterModelOptions(
            name='ordine',
            options={'verbose_name_plural': 'Ordini'},
        ),
        migrations.AlterModelOptions(
            name='prodotto',
            options={'verbose_name_plural': 'Prodotti'},
        ),
    ]
